@startuml Pipeline Flowchart
|ANC|
package "anc.m" {
    :start|
    :initializate settings;
    :read parameters;
    :load data;
    :record audio;
    :simulate adaptive filters;
    :optimize parameters;
    :noise reduction on noisy speech;
    :end|
}
stop
@enduml
