@startuml Pipeline Flowchart
|ANC|
package "anc.m" {
    :start|
    :initializate settings;
    :set modes;
    :set plots;
    :load data;
    :initialize parameters;
    :simulate adaptive filters;
    :optimize parameters;
    :noise reduction on noisy speech;
    :end|
}
stop
@enduml
